### PR TITLE
Moved contextIdReducer, groupsDataReducer, groupsIndexReducer, commentsReducer, VerseEditsReducer, BookmarksReducer, SelectionsReducer to tools codebase

### PR DESCRIPTION
**Pull request by mannycolon**
## Test instructions

- ### DO NOT MERGE UNTIL ALL PRs ARE READY TO BE MERGED 
- In translationCore repo checkout `feature-mannycolon-6501`
- run `rm -rf node_modules`  & `npm i`
- Open the app and test thoroughly  
- tN, Tw & wA tools should all work correctly

This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/checking-tool-wrapper/79)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
LGTM - code review

**Comment by PhotoNomad0** [comment]
In tW tool, when I edit verse it does change, but see no edit indication on the verse.

**Comment by mannycolon** [comment]
@PhotoNomad0 That is part of #6656

**Comment by mannycolon** [comment]
@PhotoNomad0 That is part of #6656

**Comment by PhotoNomad0** [comment]
@mannycolon - I don't see anything about verse edit indications in issue #6656.  Maybe we could add this failure to #6656. so it will be testable?  Would be good to have a list for QA of known issues.

Any other problems I should ignore for testing these PRs?

**Comment by PhotoNomad0** [comment]
@mannycolon - tested in tN and verse edit indication does work.  Very strange since they are mostly the same code.

**Comment by PhotoNomad0** [comment]
@mannycolon - verse edit indications are now working in tW.  Wonder if it is related to the project.

**Comment by PhotoNomad0** [comment]
@mannycolon - think I have the problem narrowed down.  I see it in tW group `pure...` in Titus 1:15.  It looks like it is getting confused when there is more than one of the same check in a verse.

**Comment by mannycolon** [comment]
@PhotoNomad0 I addressed all bugs w/ invalidations and verse edits

**Comment by mannycolon** [comment]
Will need to get latest tC and checking tool branch

**Pull request merged**
